# Generated by Django 3.2.9 on 2022-04-12 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211124_1624'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadAds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_id', models.CharField(max_length=250)),
                ('created_time', models.DateField(max_length=250)),
                ('ad_id', models.CharField(max_length=250)),
                ('ad_name', models.CharField(max_length=250)),
                ('adset_id', models.CharField(max_length=250)),
                ('adset_name', models.CharField(max_length=250)),
                ('campaign_id', models.CharField(max_length=250)),
                ('campaign_name', models.CharField(max_length=250)),
                ('form_id', models.CharField(max_length=250)),
                ('full_name', models.CharField(max_length=250)),
                ('phone_number', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=250)),
                ('car_request', models.CharField(max_length=250)),
                ('agent_id', models.CharField(max_length=250)),
                ('category', models.CharField(choices=[('new_lead', 'Nuovo Lead'), ('follow_up', 'Follow Up'), ('discarded_lead', 'Lead Scartato'), ('request_in_process', 'Pratica in avanzamento'), ('client', 'Cliente')], default='nuovo_lead', max_length=250)),
                ('status', models.CharField(choices=[('did_not_answer', 'Non ha risposto'), ('to_call_again', 'Da Richiamare'), ('not_in_target', 'Non in Target'), ('fake_number', 'Numero Fake'), ('send_quotation', 'Preventivo da Inviare')], default='da_richiamare', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='LeadMSN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateField(auto_now_add=True)),
                ('full_name', models.CharField(max_length=250)),
                ('phone_number', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=250)),
                ('car_request', models.CharField(max_length=250)),
                ('agent_id', models.CharField(max_length=250)),
                ('category', models.CharField(choices=[('new_lead', 'Nuovo Lead'), ('follow_up', 'Follow Up'), ('discarded_lead', 'Lead Scartato'), ('request_in_process', 'Pratica in avanzamento'), ('client', 'Cliente')], default='nuovo_lead', max_length=250)),
                ('status', models.CharField(choices=[('did_not_answer', 'Non ha risposto'), ('to_call_again', 'Da Richiamare'), ('not_in_target', 'Non in Target'), ('fake_number', 'Numero Fake'), ('send_quotation', 'Preventivo da Inviare')], default='da_richiamare', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='LeadWebsite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateField(auto_now_add=True)),
                ('full_name', models.CharField(max_length=250)),
                ('phone_number', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=250)),
                ('car_request', models.CharField(max_length=250)),
                ('agent_id', models.CharField(max_length=250)),
                ('category', models.CharField(choices=[('new_lead', 'Nuovo Lead'), ('follow_up', 'Follow Up'), ('discarded_lead', 'Lead Scartato'), ('request_in_process', 'Pratica in avanzamento'), ('client', 'Cliente')], default='nuovo_lead', max_length=250)),
                ('status', models.CharField(choices=[('did_not_answer', 'Non ha risposto'), ('to_call_again', 'Da Richiamare'), ('not_in_target', 'Non in Target'), ('fake_number', 'Numero Fake'), ('send_quotation', 'Preventivo da Inviare')], default='da_richiamare', max_length=250)),
            ],
        ),
    ]
