# Generated by Django 3.2.9 on 2022-04-13 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_leadadsbackup'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leadbackup_date', models.DateField(auto_now_add=True)),
                ('leadbackup_backup', models.TextField(max_length=2000)),
            ],
        ),
        migrations.DeleteModel(
            name='LeadAdsBackup',
        ),
    ]
