# Generated by Django 3.2.9 on 2022-04-13 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_leadbackup_leadbackup_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadmsn',
            name='created_time',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='leadwebsite',
            name='created_time',
            field=models.CharField(max_length=250),
        ),
    ]
