# Generated by Django 3.2.9 on 2022-04-20 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_loglead'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leadads',
            options={'verbose_name_plural': 'Lead Ads'},
        ),
        migrations.AlterField(
            model_name='leadads',
            name='agent_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
