# Generated by Django 3.2.9 on 2022-04-23 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20220420_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadads',
            name='agent_id',
            field=models.CharField(default='empty', max_length=250),
            preserve_default=False,
        ),
    ]
